- name: Ensure dependencies for Terraform are installed
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
      - curl
    state: present
    update_cache: yes

- name: Download HashiCorp official GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: "0644"

- name: Add HashiCorp official Apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp
    update_cache: yes

- name: Install Terraform CLI
  ansible.builtin.apt:
    name: terraform
    state: present