ansible_user: maksym23102006_gmail_com
ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

app_dir: /opt/todo-app
postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"